### ISSUE TITLE
do-release-upgrade 20.04 to 20.10 failure

### ISSUE THREAD

**Issue by stancheff** [pop-os/upgrade#194]
No snaps are installed yet. Try 'snap install hello-world'.

Checking for installed snaps

Calculating snap size requirements

Updating repository information

Traceback (most recent call last):
  File "/tmp/ubuntu-release-upgrader-qkrgga7j/groovy", line 8, in <module>
    sys.exit(main())
  File "/tmp/ubuntu-release-upgrader-qkrgga7j/DistUpgrade/DistUpgradeMain.py", line 238, in main
    if app.run():
  File "/tmp/ubuntu-release-upgrader-qkrgga7j/DistUpgrade/DistUpgradeController.py", line 2092, in run
    return self.fullUpgrade()
  File "/tmp/ubuntu-release-upgrader-qkrgga7j/DistUpgrade/DistUpgradeController.py", line 1933, in fullUpgrade
    if not self.updateSourcesList():
  File "/tmp/ubuntu-release-upgrader-qkrgga7j/DistUpgrade/DistUpgradeController.py", line 801, in updateSourcesList
    self.sources = SourcesList(matcherPath=self.datadir)
  File "/usr/lib/python3/dist-packages/aptsources/sourceslist.py", line 273, in __init__
    self.matcher = SourceEntryMatcher(matcherPath)
  File "/usr/lib/python3/dist-packages/aptsources/sourceslist.py", line 470, in __init__
    dist = DistInfo(base_dir=matcherPath)
  File "/usr/lib/python3/dist-packages/aptsources/distinfo.py", line 184, in __init__
    with open(dist_fname) as dist_file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ubuntu-release-upgrader-qkrgga7j/Pop.info'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/problem_report.py", line 477, in add_to_existing
    self.write(f)
  File "/usr/lib/python3/dist-packages/problem_report.py", line 430, in write
    block = f.read(1048576)
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

Original exception was:
Traceback (most recent call last):
  File "/tmp/ubuntu-release-upgrader-qkrgga7j/groovy", line 8, in <module>
    sys.exit(main())
  File "/tmp/ubuntu-release-upgrader-qkrgga7j/DistUpgrade/DistUpgradeMain.py", line 238, in main
    if app.run():
  File "/tmp/ubuntu-release-upgrader-qkrgga7j/DistUpgrade/DistUpgradeController.py", line 2092, in run
    return self.fullUpgrade()
  File "/tmp/ubuntu-release-upgrader-qkrgga7j/DistUpgrade/DistUpgradeController.py", line 1933, in fullUpgrade
    if not self.updateSourcesList():
  File "/tmp/ubuntu-release-upgrader-qkrgga7j/DistUpgrade/DistUpgradeController.py", line 801, in updateSourcesList
    self.sources = SourcesList(matcherPath=self.datadir)
  File "/usr/lib/python3/dist-packages/aptsources/sourceslist.py", line 273, in __init__
    self.matcher = SourceEntryMatcher(matcherPath)
  File "/usr/lib/python3/dist-packages/aptsources/sourceslist.py", line 470, in __init__
    dist = DistInfo(base_dir=matcherPath)
  File "/usr/lib/python3/dist-packages/aptsources/distinfo.py", line 184, in __init__
    with open(dist_fname) as dist_file:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/ubuntu-release-upgrader-qkrgga7j/Pop.info'
=== Command terminated with exit status 1 (Mon Jul 19 15:15:17 2021) ===

**Comment by jacobgkau** [comment]
The `do-release-upgrade` command is not supported on Pop!_OS. Please use `pop-upgrade release upgrade` instead.

There is an issue open to make `do-release-upgrade` unavailable since it is unsupported: https://github.com/pop-os/upgrade/issues/177
